import type { FieldDef } from "./schema";

// Additional page fields, shared by the editor and public renderers.
export const EXTRA_FIELDS: Record<string, Record<string, FieldDef[]>> = {
  home: {
    hero: [
      {"key":"flipHint","label":"Product picture instruction","kind":"text","fallback":"Tap or drag to flip","max":80},
      {"key":"chip1","label":"Product picture label 1","kind":"text","fallback":"New reading every minute","max":100},
      {"key":"chip2","label":"Product picture label 2","kind":"text","fallback":"Up to 14-day wear","max":100},
      {"key":"chip3","label":"Product picture label 3","kind":"text","fallback":"No routine finger sticks","max":100},
    ],
    process: [
      {"key":"getting-started","label":"Getting started","kind":"text","fallback":"Getting started","max":240},
      {"key":"a-simpler-way-to-check-your-cgm-options","label":"A Simpler Way to Check Your CGM Options","kind":"text","fallback":"A Simpler Way to Check Your CGM Options","max":240},
      {"key":"not-sure-what-your-insurance-may-cover-or-what-comes-next-start-w","label":"Not sure what your insurance may cover or what comes next? Start wi...","kind":"longText","fallback":"Not sure what your insurance may cover or what comes next? Start with a few basic details and we will help you navigate the process.","max":300},
      {"key":"step","label":"STEP","kind":"text","fallback":"STEP","max":240},
      {"key":"steps.0.title","label":"steps 1 title","kind":"text","fallback":"Tell Us About Yourself","max":240},
      {"key":"steps.0.body","label":"steps 1 body","kind":"text","fallback":"Complete our short eligibility form with your basic information so we can get started.","max":240},
      {"key":"steps.0.image","label":"steps 1 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678443/medville/migrated/d8dcbb474d0fe00a6c364302.webp","max":2048},
      {"key":"steps.0.alt","label":"steps 1 alt","kind":"text","fallback":"A person completes a short eligibility form on a smartphone at home.","max":240},
      {"key":"steps.1.title","label":"steps 2 title","kind":"text","fallback":"We Review Your Potential Eligibility","max":240},
      {"key":"steps.1.body","label":"steps 2 body","kind":"longText","fallback":"Our team reviews the information you provide and checks available coverage information to help determine your potential eligibility.","max":300},
      {"key":"steps.1.image","label":"steps 2 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678444/medville/migrated/84bf33a56417b8e28f204015.webp","max":2048},
      {"key":"steps.1.alt","label":"steps 2 alt","kind":"text","fallback":"A Medville Diabetes team member reviews information at a computer.","max":240},
      {"key":"steps.2.title","label":"steps 3 title","kind":"text","fallback":"We Walk You Through What Comes Next","max":240},
      {"key":"steps.2.body","label":"steps 3 body","kind":"longText","fallback":"We will contact you to explain what we found, answer your questions, and help you understand the next steps.","max":300},
      {"key":"steps.2.image","label":"steps 3 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678445/medville/migrated/aabb5b234cb80a4ce6b1431c.webp","max":2048},
      {"key":"steps.2.alt","label":"steps 3 alt","kind":"text","fallback":"A customer speaks with a Medville Diabetes representative by phone at home.","max":240},
    ],
    products: [
      {"key":"explore-diabetes-technology","label":"Explore diabetes technology","kind":"text","fallback":"Explore diabetes technology","max":240},
      {"key":"find-what-fits-your-routine","label":"Find What Fits Your Routine","kind":"text","fallback":"Find What Fits Your Routine","max":240},
      {"key":"from-continuous-glucose-monitors-to-insulin-delivery-technology-e","label":"From continuous glucose monitors to insulin delivery technology, ex...","kind":"longText","fallback":"From continuous glucose monitors to insulin delivery technology, explore trusted products designed to support diabetes management in everyday life.","max":300},
      {"key":"view-all-products","label":"View All Products","kind":"text","fallback":"View All Products","max":240},
    ],
    whyCgm: [
      {"key":"why-cgm","label":"Why CGM?","kind":"text","fallback":"Why CGM?","max":240},
      {"key":"more-insight-less-interruption","label":"More Insight. Less Interruption.","kind":"text","fallback":"More Insight. Less Interruption.","max":240},
      {"key":"section-photograph","label":"Section photograph","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678446/medville/migrated/5c69689deb0d4c56447b8c30.webp","max":2048},
      {"key":"photograph-description","label":"Photograph description","kind":"longText","fallback":"A woman wearing a sensor on her arm looks at her phone, which shows a glucose reading of 112 inside her target range.","max":300},
      {"key":"benefits.0.title","label":"benefits 1 title","kind":"text","fallback":"See More Than a Single Reading","max":240},
      {"key":"benefits.0.body","label":"benefits 1 body","kind":"longText","fallback":"A CGM provides glucose information throughout the day, giving you a broader view of how your glucose is changing over time.","max":300},
      {"key":"benefits.1.title","label":"benefits 2 title","kind":"text","fallback":"Check With Less Disruption","max":240},
      {"key":"benefits.1.body","label":"benefits 2 body","kind":"longText","fallback":"Compatible CGM systems can provide glucose information on a smartphone, receiver, or connected device, helping reduce the need to stop what you are doing for every check.","max":400},
      {"key":"benefits.2.title","label":"benefits 3 title","kind":"text","fallback":"Understand Your Trends","max":240},
      {"key":"benefits.2.body","label":"benefits 3 body","kind":"longText","fallback":"Seeing glucose patterns over time can give you and your healthcare provider more context around how food, activity, medication, sleep, and other factors relate to your glucose.","max":400},
      {"key":"captions.0.text","label":"captions 1 text","kind":"text","fallback":"Glucose information throughout your day.","max":240},
      {"key":"captions.1.text","label":"captions 2 text","kind":"text","fallback":"Trends you can see over time.","max":240},
      {"key":"captions.2.text","label":"captions 3 text","kind":"text","fallback":"Technology designed to fit into real life.","max":240},
    ],
    testimonials: [
      {"key":"real-life-experiences","label":"Real life experiences","kind":"text","fallback":"Real life experiences","max":240},
      {"key":"do-not-take-our-word-for-it-take-theirs","label":"Do not take our word for it. Take theirs.","kind":"text","fallback":"Do not take our word for it. Take theirs.","max":240},
      {"key":"individual-experiences-vary-testimonials-do-not-guarantee-eligibi","label":"Individual experiences vary. Testimonials do not guarantee eligibil...","kind":"longText","fallback":"Individual experiences vary. Testimonials do not guarantee eligibility, insurance coverage, product availability, or results.","max":300},
    ],
    cta: [
      {"key":"wondering-if-your-insurance-may-help-cover-a-cgm","label":"Wondering If Your Insurance May Help Cover a CGM?","kind":"text","fallback":"Wondering If Your Insurance May Help Cover a CGM?","max":240},
      {"key":"it-only-takes-a-few-minutes-to-get-started-submit-your-informatio","label":"It only takes a few minutes to get started. Submit your information...","kind":"longText","fallback":"It only takes a few minutes to get started. Submit your information and our team can review your potential eligibility and help you understand what comes next.","max":400},
      {"key":"your-information-will-be-handled-according-to-our","label":"Your information will be handled according to our","kind":"text","fallback":"Your information will be handled according to our","max":240},
      {"key":"privacy-policy","label":"Privacy Policy","kind":"text","fallback":"Privacy Policy","max":240},
      {"key":"and-applicable-privacy-requirements","label":"and applicable privacy requirements.","kind":"text","fallback":"and applicable privacy requirements.","max":240},
    ],
    blog: [
      {"key":"read-our-blog","label":"Read our blog","kind":"text","fallback":"Read our blog","max":240},
      {"key":"min-read","label":"min read","kind":"text","fallback":"min read","max":240},
      {"key":"read-the-article","label":"Read the article","kind":"text","fallback":"Read the article","max":240},
    ],
    faqs: [
      {"key":"common-questions","label":"Common questions","kind":"text","fallback":"Common questions","max":240},
      {"key":"questions-start-here","label":"Questions? Start Here.","kind":"text","fallback":"Questions? Start Here.","max":240},
    ],
    stats: [
      {"key":"years","label":"Years of experience","kind":"text","fallback":"15","max":9},
      {"key":"products","label":"Number of products","kind":"text","fallback":"35000","max":9},
      {"key":"makers","label":"Number of manufacturers","kind":"text","fallback":"300","max":9},
      {"key":"providers","label":"Number of providers","kind":"text","fallback":"6000","max":9},
      {"key":"numbers.0.label","label":"numbers 1 label","kind":"text","fallback":"Years of medical supply experience","max":240},
      {"key":"numbers.1.label","label":"numbers 2 label","kind":"text","fallback":"Products across the Medville network","max":240},
      {"key":"numbers.2.label","label":"numbers 3 label","kind":"text","fallback":"Manufacturers represented","max":240},
      {"key":"numbers.3.label","label":"numbers 4 label","kind":"text","fallback":"Care providers supported nationwide","max":240},
    ],
  },
  products: {
    catalog: [
      {"key":"categories.0.cta","label":"CGM category button","kind":"text","fallback":"Explore CGMs","max":80},
      {"key":"categories.1.cta","label":"Insulin pump category button","kind":"text","fallback":"Explore Insulin Pumps","max":80},
      {"key":"high","label":"high","kind":"text","fallback":"high","max":240},
      {"key":"auto","label":"auto","kind":"text","fallback":"auto","max":240},
      {"key":"product","label":"product","kind":"text","fallback":"product","max":240},
      {"key":"products","label":"products","kind":"text","fallback":"products","max":240},
      {"key":"categories.0.title","label":"categories 1 title","kind":"text","fallback":"Continuous Glucose Monitors","max":240},
      {"key":"categories.0.body.0","label":"categories 1 body 1","kind":"longText","fallback":"See your glucose information and trends throughout the day with CGM technology from FreeStyle Libre and Dexcom.","max":300},
      {"key":"categories.0.body.1","label":"categories 1 body 2","kind":"longText","fallback":"Whether you are exploring CGM for the first time or looking for ongoing supplies, browse the systems and sensors available through Medville Diabetes.","max":300},
      {"key":"categories.0.image","label":"categories 1 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678461/medville/migrated/c95251791956e1d4c4ba48ec.webp","max":2048},
      {"key":"categories.0.alt","label":"categories 1 alt","kind":"text","fallback":"A FreeStyle Libre 3 continuous glucose monitor box and sensor.","max":240},
      {"key":"categories.1.title","label":"categories 2 title","kind":"text","fallback":"Insulin Pumps","max":240},
      {"key":"categories.1.body.0","label":"categories 2 body 1","kind":"longText","fallback":"Explore insulin pump technology designed to provide continuous insulin delivery for people whose diabetes care requires insulin.","max":300},
      {"key":"categories.1.image","label":"categories 2 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678465/medville/migrated/72273fac98e31785fc1d3960.webp","max":2048},
      {"key":"categories.1.alt","label":"categories 2 alt","kind":"text","fallback":"A Tandem t:slim X2 insulin pump with a touchscreen, next to a sensor.","max":240},
    ],
  },
  services: {
    cycle: [
      {"key":"phases.0.label","label":"Care cycle step 1 title","kind":"text","fallback":"Calling","max":240},
      {"key":"phases.0.detail","label":"Care cycle step 1 description","kind":"longText","fallback":"You tell us what you need.","max":240},
      {"key":"phases.0.node","label":"Care cycle step 1 diagram label","kind":"text","fallback":"Call","max":240},
      {"key":"phases.1.label","label":"Care cycle step 2 title","kind":"text","fallback":"Verifying","max":240},
      {"key":"phases.1.detail","label":"Care cycle step 2 description","kind":"longText","fallback":"We confirm care and coverage.","max":240},
      {"key":"phases.1.node","label":"Care cycle step 2 diagram label","kind":"text","fallback":"Verify","max":240},
      {"key":"phases.2.label","label":"Care cycle step 3 title","kind":"text","fallback":"Preparing","max":240},
      {"key":"phases.2.detail","label":"Care cycle step 3 description","kind":"longText","fallback":"We organize the order and supplies.","max":240},
      {"key":"phases.2.node","label":"Care cycle step 3 diagram label","kind":"text","fallback":"Prepare","max":240},
      {"key":"phases.3.label","label":"Care cycle step 4 title","kind":"text","fallback":"Delivering","max":240},
      {"key":"phases.3.detail","label":"Care cycle step 4 description","kind":"longText","fallback":"Your package moves to your home.","max":240},
      {"key":"phases.3.node","label":"Care cycle step 4 diagram label","kind":"text","fallback":"Deliver","max":240},
      {"key":"phases.4.label","label":"Care cycle step 5 title","kind":"text","fallback":"Received","max":240},
      {"key":"phases.4.detail","label":"Care cycle step 5 description","kind":"longText","fallback":"Your supplies arrive at your door.","max":240},
      {"key":"phases.4.node","label":"Care cycle step 5 diagram label","kind":"text","fallback":"Receive","max":240},
      {"key":"phases.5.label","label":"Care cycle step 6 title","kind":"text","fallback":"Resupply","max":240},
      {"key":"phases.5.detail","label":"Care cycle step 6 description","kind":"longText","fallback":"The cycle continues when you need more.","max":240},
      {"key":"phases.5.node","label":"Care cycle step 6 diagram label","kind":"text","fallback":"Resupply","max":240},

      {"key":"loading-care-cycle","label":"Loading care cycle","kind":"text","fallback":"Loading care cycle","max":240},
    ],
    hero: [
      {"key":"see-the-journey","label":"See the journey","kind":"text","fallback":"See the journey","max":240},
      {"key":"the-whole-process-made-clear-in-three-steps","label":"The whole process, made clear in three steps.","kind":"text","fallback":"The whole process, made clear in three steps.","max":240},
      {"key":"one-coordinated-team","label":"One coordinated team","kind":"text","fallback":"One coordinated team","max":240},
      {"key":"we-make-the-next-step-easier-to-see","label":"We make the next step easier to see.","kind":"text","fallback":"We make the next step easier to see.","max":240},
      {"key":"from-call-to-resupply","label":"From call to resupply","kind":"text","fallback":"From call to resupply","max":240},
    ],
    stages: [
      {"key":"step","label":"Step","kind":"text","fallback":"Step","max":240},
      {"key":"what-our-team-does-in-this-step","label":"What our team does in this step","kind":"text","fallback":"What our team does in this step","max":240},
      {"key":"stages.0.title","label":"stages 1 title","kind":"text","fallback":"Tell Us About Yourself","max":240},
      {"key":"stages.0.copy","label":"stages 1 copy","kind":"text","fallback":"Complete our short eligibility form with your basic information so we can get started.","max":240},
      {"key":"stages.0.label","label":"stages 1 label","kind":"text","fallback":"Your first conversation","max":240},
      {"key":"stages.0.image","label":"stages 1 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678467/medville/migrated/ae2ee892ea4486576ba0c1de.webp","max":2048},
      {"key":"stages.0.alt","label":"stages 1 alt","kind":"text","fallback":"A woman at home begins a phone conversation about her CGM supplies.","max":240},
      {"key":"stages.0.steps.0.title","label":"stages 1 steps 1 title","kind":"text","fallback":"Intake and sales","max":240},
      {"key":"stages.0.steps.0.team","label":"stages 1 steps 1 team","kind":"text","fallback":"We introduce the CGM option and collect your contact, insurance, and diabetes information.","max":240},
      {"key":"stages.1.title","label":"stages 2 title","kind":"text","fallback":"We Review Your Potential Eligibility","max":240},
      {"key":"stages.1.copy","label":"stages 2 copy","kind":"longText","fallback":"Our team reviews the information you provide and checks available coverage information to help determine your potential eligibility.","max":300},
      {"key":"stages.1.label","label":"stages 2 label","kind":"text","fallback":"Coverage and eligibility","max":240},
      {"key":"stages.1.image","label":"stages 2 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678469/medville/migrated/ecac64179b08172654d46658.webp","max":2048},
      {"key":"stages.1.alt","label":"stages 2 alt","kind":"text","fallback":"A coordinator verifies insurance information for continuous glucose monitor coverage.","max":240},
      {"key":"stages.1.steps.0.title","label":"stages 2 steps 1 title","kind":"text","fallback":"Doctor verification and initial contact","max":240},
      {"key":"stages.1.steps.0.team","label":"stages 2 steps 1 team","kind":"text","fallback":"We contact your clinic to confirm your diabetes care and the key office details.","max":240},
      {"key":"stages.1.steps.1.title","label":"stages 2 steps 2 title","kind":"text","fallback":"Qualification","max":240},
      {"key":"stages.1.steps.1.team","label":"stages 2 steps 2 team","kind":"text","fallback":"We evaluate clinical and insurance information against the applicable CGM coverage requirements.","max":240},
      {"key":"stages.1.steps.2.title","label":"stages 2 steps 3 title","kind":"text","fallback":"Documentation retrieval","max":240},
      {"key":"stages.1.steps.2.team","label":"stages 2 steps 3 team","kind":"text","fallback":"We request the medical records, prescription, and supporting documents from your provider.","max":240},
      {"key":"stages.1.steps.3.title","label":"stages 2 steps 4 title","kind":"text","fallback":"Documentation review and compliance","max":240},
      {"key":"stages.1.steps.3.team","label":"stages 2 steps 4 team","kind":"text","fallback":"We check documents for accuracy, completion, and payer requirements.","max":240},
      {"key":"stages.1.steps.4.title","label":"stages 2 steps 5 title","kind":"text","fallback":"Insurance verification and authorization","max":240},
      {"key":"stages.1.steps.4.team","label":"stages 2 steps 5 team","kind":"text","fallback":"We verify coverage and obtain required authorization or follow-up information.","max":240},
      {"key":"stages.2.title","label":"stages 3 title","kind":"text","fallback":"We Walk You Through What Comes Next","max":240},
      {"key":"stages.2.copy","label":"stages 3 copy","kind":"longText","fallback":"We will contact you to explain what we found, answer your questions, and help you understand the next steps.","max":300},
      {"key":"stages.2.label","label":"stages 3 label","kind":"text","fallback":"Delivery and ongoing support","max":240},
      {"key":"stages.2.image","label":"stages 3 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678470/medville/migrated/c230690d42cb5175fcc59880.webp","max":2048},
      {"key":"stages.2.alt","label":"stages 3 alt","kind":"text","fallback":"A CGM supply kit is carefully prepared in a white box.","max":240},
      {"key":"stages.2.steps.0.title","label":"stages 3 steps 1 title","kind":"text","fallback":"Order processing","max":240},
      {"key":"stages.2.steps.0.team","label":"stages 3 steps 1 team","kind":"text","fallback":"Once requirements are met, we process the order for the appropriate CGM and supplies.","max":240},
      {"key":"stages.2.steps.1.title","label":"stages 3 steps 2 title","kind":"text","fallback":"Shipping and delivery","max":240},
      {"key":"stages.2.steps.1.team","label":"stages 3 steps 2 team","kind":"text","fallback":"We ship the CGM directly to your home.","max":240},
      {"key":"stages.2.steps.2.title","label":"stages 3 steps 3 title","kind":"text","fallback":"Customer service and support","max":240},
      {"key":"stages.2.steps.2.team","label":"stages 3 steps 3 team","kind":"text","fallback":"We help with questions, concerns, and equipment or supply issues.","max":240},
      {"key":"stages.2.steps.3.title","label":"stages 3 steps 4 title","kind":"text","fallback":"Reorder and resupply","max":240},
      {"key":"stages.2.steps.3.team","label":"stages 3 steps 4 team","kind":"text","fallback":"We maintain eligibility and documentation while supporting ongoing resupply shipments.","max":240},
    ],
    closing: [
      {"key":"the-full-care-path","label":"The full care path","kind":"text","fallback":"The full care path","max":240},
    ],
  },
  about: {
    hero: [
      {"key":"medville-diabetes-brings-the-medical-supply-experience-of-medvill","label":"Medville Diabetes brings the medical supply experience of Medville ...","kind":"longText","fallback":"Medville Diabetes brings the medical supply experience of Medville into a service focused specifically on diabetes, helping make access to CGMs and other diabetes supplies simpler and easier to navigate.","max":500},
      {"key":"photograph-description","label":"Photograph description","kind":"text","fallback":"A woman wearing a continuous glucose monitor on her arm checks a reading at her kitchen table.","max":240},
      {"key":"promises.0.lines.0","label":"promises 1 lines 1","kind":"text","fallback":"We handle","max":240},
      {"key":"promises.0.lines.1","label":"promises 1 lines 2","kind":"text","fallback":"the paperwork","max":240},
      {"key":"promises.1.lines.0","label":"promises 2 lines 1","kind":"text","fallback":"Delivered","max":240},
      {"key":"promises.1.lines.1","label":"promises 2 lines 2","kind":"text","fallback":"to your door","max":240},
      {"key":"promises.2.lines.0","label":"promises 3 lines 1","kind":"text","fallback":"Real people,","max":240},
      {"key":"promises.2.lines.1","label":"promises 3 lines 2","kind":"text","fallback":"real support","max":240},
      {"key":"promises.3.lines.0","label":"promises 4 lines 1","kind":"text","fallback":"Trusted brands.","max":240},
      {"key":"promises.3.lines.1","label":"promises 4 lines 2","kind":"text","fallback":"Reliable care.","max":240},
    ],
    missionVision: [
      {"key":"why-we-are-here","label":"Why we are here","kind":"text","fallback":"Why we are here","max":240},
      {"key":"built-around-what-makes-diabetes-care-easier","label":"Built Around What Makes Diabetes Care Easier","kind":"text","fallback":"Built Around What Makes Diabetes Care Easier","max":240},
      {"key":"cards.0.title","label":"cards 1 title","kind":"text","fallback":"Our Mission","max":240},
      {"key":"cards.0.body","label":"cards 1 body","kind":"longText","fallback":"Our mission is to make getting diabetes supplies easier, more dependable, and less stressful. We combine access to trusted products with clear communication and responsive support, helping people navigate the supply process without adding more unnecessary work to diabetes management.","max":600},
      {"key":"cards.0.image","label":"cards 1 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678409/medville/migrated/66712e3bbe59f8f86d2b50ce.webp","max":2048},
      {"key":"cards.0.alt","label":"cards 1 alt","kind":"text","fallback":"A pharmacy delivery is handed to a smiling woman at her front door.","max":240},
      {"key":"cards.1.title","label":"cards 2 title","kind":"text","fallback":"Our Vision","max":240},
      {"key":"cards.1.body","label":"cards 2 body","kind":"longText","fallback":"Our vision is a diabetes supply experience that fits more naturally into everyday life, where people spend less time chasing answers, worrying about supplies, or trying to figure out what comes next. We want dependable access and helpful support to feel like the standard, giving the people we serve more time and confidence to focus on everything beyond managing diabetes.","max":800},
      {"key":"cards.1.image","label":"cards 2 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678413/medville/migrated/d6194a26f3394385532c7685.webp","max":2048},
      {"key":"cards.1.alt","label":"cards 2 alt","kind":"text","fallback":"A family shares a meal in the garden while one of them checks a glucose reading on her phone.","max":240},
    ],
    story: [
      {"key":"backed-by-medville","label":"Backed by Medville","kind":"text","fallback":"Backed by Medville","max":240},
      {"key":"medical-supply-experience-with-a-focus-on-diabetes","label":"Medical Supply Experience With a Focus on Diabetes","kind":"text","fallback":"Medical Supply Experience With a Focus on Diabetes","max":240},
      {"key":"reliable-supplies-dedicated-support-more-time-for-life","label":"Reliable supplies. Dedicated support. More time for life.","kind":"text","fallback":"Reliable supplies. Dedicated support. More time for life.","max":240},
    ],
    promises: [
      {"key":"three-promises","label":"Three promises","kind":"text","fallback":"Three promises","max":240},
      {"key":"what-you-can-expect-from-us","label":"What You Can Expect From Us","kind":"text","fallback":"What You Can Expect From Us","max":240},
      {"key":"cards.0.title","label":"cards 1 title","kind":"text","fallback":"Dependable Supplies","max":240},
      {"key":"cards.0.body","label":"cards 1 body","kind":"longText","fallback":"Getting the supplies you rely on should not feel uncertain. We work to provide dependable access to diabetes products and help make ongoing supply needs easier to manage.","max":400},
      {"key":"cards.0.image","label":"cards 1 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678410/medville/migrated/7a42be8d1f2b96b1a4c62250.webp","max":2048},
      {"key":"cards.0.alt","label":"cards 1 alt","kind":"text","fallback":"A FreeStyle Libre box and a Dexcom box with their sensors in front.","max":240},
      {"key":"cards.1.title","label":"cards 2 title","kind":"text","fallback":"Clear Communication","max":240},
      {"key":"cards.1.body","label":"cards 2 body","kind":"longText","fallback":"You should not have to chase down answers. We keep you informed and help explain what comes next throughout the supply process.","max":300},
      {"key":"cards.1.image","label":"cards 2 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678411/medville/migrated/57b933eb57e05842013512ec.webp","max":2048},
      {"key":"cards.1.alt","label":"cards 2 alt","kind":"text","fallback":"A clipboard with three completed checks, next to a speech bubble and a small plant.","max":240},
      {"key":"cards.2.title","label":"cards 3 title","kind":"text","fallback":"Support When You Need It","max":240},
      {"key":"cards.2.body","label":"cards 3 body","kind":"longText","fallback":"Questions happen. Our team is here to help you navigate supply-related questions, potential eligibility, and next steps without adding more confusion.","max":300},
      {"key":"cards.2.image","label":"cards 3 image","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678412/medville/migrated/6dd33173a50411fd3bfc41ac.webp","max":2048},
      {"key":"cards.2.alt","label":"cards 3 alt","kind":"text","fallback":"A shield with a lock in front of a database and a cloud.","max":240},
    ],
    closing: [
      {"key":"ready-to-make-getting-your-supplies-easier","label":"Ready to Make Getting Your Supplies Easier?","kind":"text","fallback":"Ready to Make Getting Your Supplies Easier?","max":240},
      {"key":"start-by-checking-your-potential-cgm-eligibility-and-let-us-help-","label":"Start by checking your potential CGM eligibility and let us help yo...","kind":"text","fallback":"Start by checking your potential CGM eligibility and let us help you understand what comes next.","max":240},
      {"key":"check-my-eligibility","label":"Check My Eligibility","kind":"text","fallback":"Check My Eligibility","max":240},
    ],
  },
  contact: {
    form: [
      {"key":"your-message-was-sent","label":"Your message was sent","kind":"text","fallback":"Your message was sent","max":240},
      {"key":"our-team-will-review-your-general-question-and-contact-you-using-","label":"Our team will review your general question and contact you using th...","kind":"text","fallback":"Our team will review your general question and contact you using the details you provided.","max":240},
      {"key":"return-home","label":"Return home","kind":"text","fallback":"Return home","max":240},
      {"key":"send-a-general-question","label":"Send a general question","kind":"text","fallback":"Send a general question","max":240},
      {"key":"all-fields-are-required","label":"All fields are required.","kind":"text","fallback":"All fields are required.","max":240},
      {"key":"your-contact-information-and-question","label":"Your contact information and question","kind":"text","fallback":"Your contact information and question","max":240},
      {"key":"first-name","label":"First Name","kind":"text","fallback":"First Name","max":240},
      {"key":"last-name","label":"Last Name","kind":"text","fallback":"Last Name","max":240},
      {"key":"email-address","label":"Email Address","kind":"text","fallback":"Email Address","max":240},
      {"key":"phone-number","label":"Phone Number","kind":"text","fallback":"Phone Number","max":240},
      {"key":"city","label":"City","kind":"text","fallback":"City","max":240},
      {"key":"state","label":"State","kind":"text","fallback":"State","max":240},
      {"key":"select-your-state","label":"Select your state","kind":"text","fallback":"Select your state","max":240},
      {"key":"how-can-we-help-you","label":"How can we help you?","kind":"text","fallback":"How can we help you?","max":240},
      {"key":"i-confirm-that-this-message-contains-only-a-general-question-and-","label":"I confirm that this message contains only a general question and do...","kind":"longText","fallback":"I confirm that this message contains only a general question and does not include medical records, health information, insurance identifiers, or other sensitive personal information.","max":400},
      {"key":"your-message-could-not-be-sent-please-try-again-or-call-our-team","label":"Your message could not be sent. Please try again or call our team.","kind":"text","fallback":"Your message could not be sent. Please try again or call our team.","max":240},
      {"key":"sending-your-message","label":"Sending your message","kind":"text","fallback":"Sending your message","max":240},
      {"key":"send-message","label":"Send message","kind":"text","fallback":"Send message","max":240},
      {"key":"we-handle-your-contact-details-according-to-our","label":"We handle your contact details according to our","kind":"text","fallback":"We handle your contact details according to our","max":240},
      {"key":"privacy-policy","label":"Privacy Policy","kind":"text","fallback":"Privacy Policy","max":240},
      {"key":"before-you-continue","label":"Before you continue","kind":"text","fallback":"Before you continue","max":240},
      {"key":"please-do-not-send-health-information","label":"Please do not send health information","kind":"text","fallback":"Please do not send health information","max":240},
      {"key":"use-this-form-only-for-general-questions-about-medville-diabetes-","label":"Use this form only for general questions about Medville Diabetes pr...","kind":"text","fallback":"Use this form only for general questions about Medville Diabetes products, services, or next steps.","max":240},
      {"key":"do-not-include-medical-records-diagnoses-medications-glucose-rea","label":"Do not include medical records, diagnoses, medications, glucose rea...","kind":"longText","fallback":"Do not include medical records, diagnoses, medications, glucose readings, insurance or Medicare numbers, Social Security numbers, medical documents, or images.","max":400},
      {"key":"continue-to-form","label":"Continue to form","kind":"text","fallback":"Continue to form","max":240},
      {"key":"call-instead","label":"Call instead","kind":"text","fallback":"Call instead","max":240},
    ],
    hero: [
      {"key":"keep-your-message-general","label":"Keep your message general","kind":"text","fallback":"Keep your message general","max":240},
      {"key":"do-not-include-diagnoses-medications-glucose-readings-insurance","label":"Do not include diagnoses, medications, glucose readings, insurance ...","kind":"longText","fallback":"Do not include diagnoses, medications, glucose readings, insurance or Medicare numbers, Social Security numbers, medical documents, or images.","max":300},
      {"key":"prefer-to-speak-with-someone","label":"Prefer to speak with someone?","kind":"text","fallback":"Prefer to speak with someone?","max":240},
      {"key":"call","label":"Call","kind":"text","fallback":"Call","max":240},
    ],
  },
  blog: {
    articles: [
      {"key":"practical-diabetes-education","label":"Practical diabetes education","kind":"text","fallback":"Practical diabetes education","max":240},
      {"key":"min-read","label":"min read","kind":"text","fallback":"min read","max":240},
      {"key":"read-article","label":"Read article","kind":"text","fallback":"Read article","max":240},
      {"key":"articles-are-coming-soon-explore-our","label":"Articles are coming soon. Explore our","kind":"text","fallback":"Articles are coming soon. Explore our","max":240},
      {"key":"cgm-products","label":"CGM products","kind":"text","fallback":"CGM products","max":240},
      {"key":"in-the-meantime","label":"in the meantime.","kind":"text","fallback":"in the meantime.","max":240},
      {"key":"start-here","label":"Start here","kind":"text","fallback":"Start here","max":240},
      {"key":"a-guide-to-glucose-monitoring","label":"A Guide to Glucose Monitoring","kind":"text","fallback":"A Guide to Glucose Monitoring","max":240},
      {"key":"read-the-guide","label":"Read the guide","kind":"text","fallback":"Read the guide","max":240},
      {"key":"article","label":"article","kind":"text","fallback":"article","max":240},
      {"key":"articles","label":"articles","kind":"text","fallback":"articles","max":240},
      {"key":"more-guides-are-on-the-way","label":"More guides are on the way.","kind":"text","fallback":"More guides are on the way.","max":240},
      {"key":"more-articles","label":"More articles","kind":"text","fallback":"More articles","max":240},
      {"key":"topics.0.label","label":"topics 1 label","kind":"text","fallback":"Glucose monitoring","max":240},
      {"key":"topics.0.description","label":"topics 1 description","kind":"text","fallback":"Understand CGMs, glucose readings, and the patterns behind them.","max":240},
      {"key":"topics.1.label","label":"topics 2 label","kind":"text","fallback":"Everyday living","max":240},
      {"key":"topics.1.description","label":"topics 2 description","kind":"text","fallback":"Practical answers about food, drinks, and life with diabetes.","max":240},
      {"key":"topics.2.label","label":"topics 3 label","kind":"text","fallback":"Supplies and coverage","max":240},
      {"key":"topics.2.description","label":"topics 3 description","kind":"text","fallback":"Know what to ask about devices, prescriptions, and insurance.","max":240},
    ],
    hero: [
      {"key":"medville-diabetes-journal","label":"Small label above the heading","kind":"text","fallback":"Medville Diabetes journal","max":240},
      {"key":"clear-answers-for-life-with-diabetes","label":"Heading","kind":"text","fallback":"Clear Answers for Life With Diabetes","max":240},
      {"key":"explore-practical-guides-to-glucose-monitoring-daily-choices-and","label":"Explore practical guides to glucose monitoring, daily choices, and ...","kind":"longText","fallback":"Explore practical guides to glucose monitoring, daily choices, and getting the supplies you need. Each article gives you useful questions to take to your healthcare team.","max":400},
    ],
    closing: [
      {"key":"need-help-with-diabetes-supplies","label":"Need help with diabetes supplies?","kind":"text","fallback":"Need help with diabetes supplies?","max":240},
      {"key":"learn-about-our-cgm-options-and-how-our-team-helps-you-navigate-t","label":"Learn about our CGM options and how our team helps you navigate the...","kind":"text","fallback":"Learn about our CGM options and how our team helps you navigate the supply process.","max":240},
      {"key":"explore-cgms","label":"Explore CGMs","kind":"text","fallback":"Explore CGMs","max":240},
      {"key":"how-we-help","label":"How we help","kind":"text","fallback":"How we help","max":240},
    ],
  },
  qualify: {
    form: [
      {"key":"productGuidance.pump","label":"Insulin pump guidance","kind":"longText","fallback":"This pump supports continuous insulin delivery through the day. Training and guidance from a qualified healthcare professional are required.","max":700},
      {"key":"productGuidance.sensor","label":"Sensor guidance","kind":"longText","fallback":"This sensor supports a compatible CGM system so you can continue seeing glucose readings and trends during daily activities.","max":700},
      {"key":"productGuidance.accessory","label":"Accessory guidance","kind":"longText","fallback":"This accessory supports a compatible CGM system so glucose information can remain available during daily routines.","max":700},
      {"key":"productGuidance.system","label":"CGM system guidance","kind":"longText","fallback":"This CGM can help you see glucose readings and trends throughout the day. The information can support conversations about food, activity, sleep, and medication with your healthcare professional.","max":700},
      {"key":"thank-you-we-received-your-information","label":"Confirmation heading","kind":"text","fallback":"Thank You. We Received Your Information.","max":240},
      {"key":"our-team-will-review-the-information-you-submitted-and-contact-yo","label":"Confirmation message","kind":"longText","fallback":"Our team will review the information you submitted and contact you to discuss your potential eligibility and available next steps. Submitting this form does not guarantee insurance coverage or qualification.","max":500},
      {"key":"explore-products","label":"Explore Products","kind":"text","fallback":"Explore Products","max":240},
      {"key":"check-your-potential-eligibility","label":"Small label above the heading","kind":"text","fallback":"Check your potential eligibility","max":240},
      {"key":"does-your-insurance-help-cover-a-cgm","label":"Heading","kind":"text","fallback":"Does Your Insurance Help Cover a CGM?","max":240},
      {"key":"not-sure-what-your-plan-may-cover-complete-the-short-form-below-a","label":"Introduction when submissions are enabled","kind":"longText","fallback":"Not sure what your plan may cover? Complete the short form below and our team will review your information to help you understand your potential eligibility and next steps.","max":400},
      {"key":"not-sure-what-your-plan-may-cover-our-team-can-review-your-inform","label":"Introduction while submissions are disabled","kind":"longText","fallback":"Not sure what your plan may cover? Our team can review your information and help you understand your potential eligibility and next steps.","max":300},
      {"key":"step","label":"STEP","kind":"text","fallback":"STEP","max":240},
      {"key":"your-privacy-matters-information-submitted-through-this-form-will","label":"Your privacy matters. Information submitted through this form will ...","kind":"text","fallback":"Your privacy matters. Information submitted through this form will be handled according to our","max":240},
      {"key":"privacy-policy","label":"Privacy Policy","kind":"text","fallback":"Privacy Policy","max":240},
      {"key":"and-applicable-privacy-requirements","label":"and applicable privacy requirements.","kind":"text","fallback":"and applicable privacy requirements.","max":240},
      {"key":"check-your-eligibility","label":"Check your eligibility","kind":"text","fallback":"Check your eligibility","max":240},
      {"key":"all-fields-are-required","label":"All fields are required.","kind":"text","fallback":"All fields are required.","max":240},
      {"key":"your-contact-details-and-eligibility-questions","label":"Your contact details and eligibility questions","kind":"text","fallback":"Your contact details and eligibility questions","max":240},
      {"key":"first-name","label":"First Name","kind":"text","fallback":"First Name","max":240},
      {"key":"last-name","label":"Last Name","kind":"text","fallback":"Last Name","max":240},
      {"key":"email-address","label":"Email Address","kind":"text","fallback":"Email Address","max":240},
      {"key":"phone-number","label":"Phone Number","kind":"text","fallback":"Phone Number","max":240},
      {"key":"city","label":"City","kind":"text","fallback":"City","max":240},
      {"key":"state","label":"State","kind":"text","fallback":"State","max":240},
      {"key":"select-your-state","label":"Select your state","kind":"text","fallback":"Select your state","max":240},
      {"key":"which-product-are-you-interested-in","label":"Which product are you interested in?","kind":"text","fallback":"Which product are you interested in?","max":240},
      {"key":"select-a-product","label":"Select a product","kind":"text","fallback":"Select a product","max":240},
      {"key":"your-selection","label":"Your selection","kind":"text","fallback":"Your selection","max":240},
      {"key":"do-you-inject-insulin-daily","label":"Do you inject insulin daily?","kind":"text","fallback":"Do you inject insulin daily?","max":240},
      {"key":"yes","label":"Yes","kind":"text","fallback":"Yes","max":240},
      {"key":"no","label":"No","kind":"text","fallback":"No","max":240},
      {"key":"something-went-wrong-while-submitting-your-information-please-try","label":"Something went wrong while submitting your information. Please try ...","kind":"longText","fallback":"Something went wrong while submitting your information. Please try again or contact our team for assistance.","max":300},
      {"key":"by-ticking-this-box-i-certify-that-i-personally-entered-my-own-in","label":"Consent statement","kind":"longText","fallback":"By ticking this box, I certify that I personally entered my own information, and I give express consent authorizing Medville Diabetes (MD), and its marketing partners to contact me at the email address and/or phone number provided (mobile phone as applicable) which may include direct calls, auto-dialed calls, text messages, and artificial or pre-recorded voice calls to discuss continuous glucose monitors and related healthcare products/services; regardless of my inclusion on any State or Federal Do Not Call list. I further certify that I am the customary user of the telephone number I have provided and am authorized to provide express consent to be contacted at this number. MD may, with your verbal consent, transfer your call to a third party for the purpose of offering other products and/or services. MD may be compensated for the call transfer. Consent is not a condition of purchase. By ticking this box, I also consent to","max":1900},
      {"key":"md-privacy-policy","label":"MD Privacy Policy","kind":"text","fallback":"MD Privacy Policy","max":240},
      {"key":"and","label":"and","kind":"text","fallback":"and","max":240},
      {"key":"md-terms-and-conditions","label":"MD Terms and Conditions","kind":"text","fallback":"MD Terms and Conditions","max":240},
      {"key":"sending-your-information","label":"Sending your information…","kind":"text","fallback":"Sending your information…","max":240},
      {"key":"check-my-eligibility","label":"Check My Eligibility","kind":"text","fallback":"Check My Eligibility","max":240},
      {"key":"you-can-review-the-form-now-submission-will-be-enabled-after-the-","label":"You can review the form now. Submission will be enabled after the r...","kind":"text","fallback":"You can review the form now. Submission will be enabled after the required compliance approval.","max":240},
      {"key":"steps.0.title","label":"steps 1 title","kind":"text","fallback":"Submit Your Details","max":240},
      {"key":"steps.0.body","label":"steps 1 body","kind":"text","fallback":"Fill out the form with your basic information.","max":240},
      {"key":"steps.1.title","label":"steps 2 title","kind":"text","fallback":"We Review","max":240},
      {"key":"steps.1.body","label":"steps 2 body","kind":"text","fallback":"We check your information and potential eligibility.","max":240},
      {"key":"steps.2.title","label":"steps 3 title","kind":"text","fallback":"We Contact You","max":240},
      {"key":"steps.2.body","label":"steps 3 body","kind":"text","fallback":"Our team reaches out to explain what comes next.","max":240},
    ],
  },
  refer: {
    hero: [
      {"key":"for-healthcare-providers","label":"Small label above the heading","kind":"text","fallback":"For healthcare providers","max":240},
      {"key":"a-simpler-way-to-refer-patients-for-diabetes-supplies","label":"Heading","kind":"text","fallback":"A Simpler Way to Refer Patients for Diabetes Supplies","max":240},
      {"key":"send-your-patient-to-medville-diabetes-and-we-will-help-guide-the","label":"Introduction","kind":"longText","fallback":"Send your patient to Medville Diabetes and we will help guide them through the supply process, from potential eligibility to next steps.","max":300},
      {"key":"contact-our-team","label":"Contact Our Team","kind":"text","fallback":"Contact Our Team","max":240},
      {"key":"simple-referral-process-clear-follow-up-support-for-your-patient","label":"Simple referral process. Clear follow-up. Support for your patient ...","kind":"text","fallback":"Simple referral process. Clear follow-up. Support for your patient along the way.","max":240},
      {"key":"section-photograph","label":"Section photograph","kind":"image","fallback":"https://res.cloudinary.com/zixjwbqv/image/upload/f_auto,q_auto,c_limit,w_1920/v1789678468/medville/migrated/feaf9b96de328d8e5b72cfa7.webp","max":2048},
      {"key":"photograph-description","label":"Photograph description","kind":"text","fallback":"A care coordinator reviews a patient's records during a routine appointment.","max":240},
    ],
    steps: [
      {"key":"how-referrals-work","label":"How referrals work","kind":"text","fallback":"How referrals work","max":240},
      {"key":"refer-in-three-simple-steps","label":"Refer in Three Simple Steps","kind":"text","fallback":"Refer in Three Simple Steps","max":240},
      {"key":"step","label":"STEP","kind":"text","fallback":"STEP","max":240},
      {"key":"cards.0.title","label":"cards 1 title","kind":"text","fallback":"Download","max":240},
      {"key":"cards.0.body","label":"cards 1 body","kind":"text","fallback":"Download the referral form and requirements in one file.","max":240},
      {"key":"cards.1.title","label":"cards 2 title","kind":"text","fallback":"Complete & Send","max":240},
      {"key":"cards.1.body","label":"cards 2 body","kind":"longText","fallback":"Complete the form and submit it with the requested documentation using the secure referral method provided.","max":300},
      {"key":"cards.2.title","label":"cards 3 title","kind":"text","fallback":"We Take It From Here","max":240},
      {"key":"cards.2.body","label":"cards 3 body","kind":"longText","fallback":"Our team reviews the referral, contacts the patient, and follows up with your office if anything else is needed.","max":300},
    ],
    video: [
      {"key":"embedUrl","label":"Video embed address","kind":"url","fallback":"","max":2048,"help":"Paste an HTTPS embed address from your video provider."},
      {"key":"see-how-it-works","label":"See how it works","kind":"text","fallback":"See how it works","max":240},
      {"key":"referral-process-in-under-a-minute","label":"Referral Process in Under a Minute","kind":"text","fallback":"Referral Process in Under a Minute","max":240},
      {"key":"a-quick-walkthrough-of-how-to-refer-a-patient-to-medville-diabete","label":"A quick walkthrough of how to refer a patient to Medville Diabetes ...","kind":"longText","fallback":"A quick walkthrough of how to refer a patient to Medville Diabetes and what happens after you submit the referral.","max":300},
      {"key":"the-referral-walkthrough-video-is-on-its-way","label":"The referral walkthrough video is on its way.","kind":"text","fallback":"The referral walkthrough video is on its way.","max":240},
      {"key":"in-the-meantime-the-three-steps-above-cover-the-whole-process-and","label":"In the meantime, the three steps above cover the whole process, and...","kind":"longText","fallback":"In the meantime, the three steps above cover the whole process, and our team is available by phone or email.","max":300},
    ],
    download: [
      {"key":"packetUrl","label":"Referral packet PDF address","kind":"url","fallback":"","max":2048,"help":"Paste the HTTPS address of the referral packet. Leave blank to use the email request option."},
      {"key":"buttonLabel","label":"Download button text","kind":"text","fallback":"Download Referral Form & Requirements","max":120},
      {"key":"ready-to-refer","label":"Ready to refer?","kind":"text","fallback":"Ready to refer?","max":240},
      {"key":"everything-you-need-in-one-download","label":"Everything You Need in One Download","kind":"text","fallback":"Everything You Need in One Download","max":240},
      {"key":"get-the-medville-diabetes-referral-form-and-requirements-together","label":"Get the Medville Diabetes referral form and requirements together i...","kind":"text","fallback":"Get the Medville Diabetes referral form and requirements together in one packet.","max":240},
      {"key":"pdf-printable-for-healthcare-provider-use","label":"PDF • Printable • For healthcare provider use","kind":"text","fallback":"PDF • Printable • For healthcare provider use","max":240},
      {"key":"send-completed-referrals-to","label":"Send completed referrals to","kind":"text","fallback":"Send completed referrals to","max":240},
      {"key":"questions","label":"Questions?","kind":"text","fallback":"Questions?","max":240},
      {"key":"call","label":"Call","kind":"text","fallback":"Call","max":240},
    ],
    support: [
      {"key":"need-help-with-a-referral","label":"Need Help With a Referral?","kind":"text","fallback":"Need Help With a Referral?","max":240},
      {"key":"have-a-question-before-sending-your-referral-or-need-help-with-an","label":"Have a question before sending your referral or need help with an e...","kind":"longText","fallback":"Have a question before sending your referral or need help with an existing patient request? Our team is here to help.","max":300},
      {"key":"contact-our-team","label":"Contact Our Team","kind":"text","fallback":"Contact Our Team","max":240},
    ],
  },
};
